name: rule_dev_tool
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  # 建议与你 3.41.6 对应的 SDK 环境保持一致
  sdk: '>=3.11.0 <4.0.0'
  flutter: '>=3.41.0'

dependencies:
  flutter:
    sdk: flutter

  # 保持现状即可
  jni: ^0.10.0
  xpath_selector_html_parser: ^3.0.1
  path_provider_android: ^2.2.4
  path_provider: ^2.1.4
  flutter_modular: ^6.3.2
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  card_settings_ui: ^2.0.1
  cupertino_icons: ^1.0.8
  html: ^0.15.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true